apiVersion: v1
kind: ConfigMap
data:
  nginx.conf: |
    worker_processes 5;
    error_log error.log;
    pid nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections 1024;
    }

    http {
      upstream backend {
        ip_hash;
        server web-main weight=9;
        server web-experiment;
      }

      server {
        access_log access.log;
        listen 0.0.0.0:80;
        location / {
          proxy_pass http://backend;
        }
      }
    }
metadata:
  name: experiment-config
