apiVersion: v1
kind: Pod
metadata:
  name: experiment-example
  labels:
    app: experiment-example
spec:
  containers:
  - name: experiment-example
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx
    ports:
    - containerPort: 80
  - name: debugger
    image: python:2.7-alpine
    command:
    - sleep
    - 999d
  volumes:
  - name: config-volume
    configMap:
      name: experiment-config
---
apiVersion: v1
kind: Service
metadata:
  name: experiment-example
  labels:
    app: experiment-example
spec:
  ports:
  - port: 80
    name: web
  type: LoadBalancer
  selector:
    app: experiment-example
