apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-experiment
  labels:
    app: web-experiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-experiment
  template:
    metadata:
      name: web-experiment
      labels:
        app: web-experiment
    spec:
      containers:
      - name: nginx-experiment
        image: nginx
        volumeMounts:
        - name: index-experiment
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      - name: debugger
        image: python:2.7-alpine
        command:
        - sleep
        - 999d
      volumes:
      - name: index-experiment
        configMap:
          name: index-experiment
---
apiVersion: v1
kind: Service
metadata:
  name: web-experiment
  labels:
    app: web-experiment
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: web
  selector:
    app: web-experiment
