apiVersion: v1
kind: Pod
metadata:
  name: web-main
  labels:
    app: web-main
spec:
  containers:
  - name: nginx-main
    image: nginx
    volumeMounts:
    - name: index-main
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
  - name: debugger
    image: python:2.7-alpine
    command:
    - sleep
    - 999d
  volumes:
  - name: index-main
    configMap:
      name: index-main
---
apiVersion: v1
kind: Service
metadata:
  name: web-main
  labels:
    app: web-main
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: web
  selector:
    app: web-main
